.\" nihtest-case.mdoc -- nihtest test case format description
.\" Copyright (C) 2020-2023 Dieter Baron and Thomas Klausner
.\"
.\" This file is part of nihtest, a testing framework.
.\" The authors can be contacted at <nihtest@nih.at>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\" 3. The names of the authors may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
.\" IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\" IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 9, 2023
.Dt NIHTEST-CASE 5
.Os
.Sh NAME
.Nm nihtest-case
.Nd test case format for nihtest
.Sh DESCRIPTION
.Xr nihtest 1
is a testing tool.
It uses
.Pa .test
files as input.
This man page describes the format of these test files.
.Pp
Lines beginning with
.Dq \&#
are comments.
.Pp
The following commands are recognized.
The
.Ic return
and
.Ic args
commands must appear exactly once, the others are optional.
.Bl -tag -width 20n
.It Ic arguments Op Ar argument ...
Run the program with command line arguments
.Ar args .
Shell style quoting is supported.
.It Ic description Ar text
Describes the purpose of the test.
.It Ic features Ar feature ...
Only run test if all
.Ar feature Ns No s
are present, otherwise skip it.
The features are extracted from a top-level
.Pa config.h
file.
If the string
.Dv HAVE_FOO
is defined in the file, the feature
.Dv FOO
is assumed to be available, otherwise not.
See also the description of
.Ic top-build-directory
in
.Xr nihtest-config 5 .
.It Ic file Ar name in Op Ar out
The arguments
.Ar in
and
.Ar out
specify the contents of the file
.Ar name
in the test directory before and after the program is run, respectively.
If
.Ar out
is omitted, the file is expected to remain unchanged.
.Pp
.Dq {}
specifies that the file does not exist (i. e. that it is created or deleted by the program).
.Pp
For
.Dq <inline>
the contents of the file are taken from the test case, up to a line consisting of
.Dq end-of-inline-data .
If both
.Ar in
and
.Ar out
are
.Dq <inline> ,
the input data comes first.
Otherwise the argument specifies the name of the file to copy or compare againts.
.It Ic mkdir Ar name
Create directory
.Ar name
 in the test directory.
.It Ic precheck Ar command Op Ar argument ...
If
.Ar command
exits with non-zero status, skip the test.
.It Ic preload Ar object
Pre-load the shared object
.Ar object
before running the program.
.Pp
This is not supported on macOS and Windows, where tests with
.Ic preload
will be skipped.
.It Ic program Ar name
Run
.Ar name .
See the description of
.Ic arguments
above for its command line arguments.
If this directive is omitted,
.Ic default-program
from
.Pa nihtest.conf
is run.
.It Ic return Ar exit-code
.Ar exit-code
is the expected exit code (usually 0 on success).
.It Ic setenv Ar variable value
Set the environment variable
.Ar variable
to
.Ar value .
.It Ic stderr Op Ar file
Specify the expect standard error output (stderr).
If
.Ar file
is given, the output is compared with that file,
otherwise the expected text is taken from the following lines of the test case, up to a line consisting of
.Dq end-of-inline-data .
.It Ic stderr-replace Ar pattern replacement
Run regular expression replacement over the standard error output
and the expected output as provided by
.Ic stderr
before comparing them.
.Ar pattern
is the match expression,
.Ar replacement
is the replacement expression.
In the replacement expression,
.Dq $1
to
.Dq $9
are replaced with the content of the corresponding
.Dq (...)
match in the
.Ar pattern .
See
.Xr re_format 7
for details.
.It Ic stdin Op Ar file
If
.Ar file
is given, standard input (stdin) is redirected from this file, which means the program has direct access to the file, including the ability to seek within it.
.Pp
Otherwise the text provided to the program via a pipe is taken from the test case, up to a line consisting of
.Dq end-of-inline-data .
.It Ic stdout Op Ar file
Specify the expect standard output (stdout).
If
.Ar file
is given, the output is compared with that file,
otherwise the expected text is taken from the following lines of the test case, up to a line consisting of
.Dq end-of-inline-data .
.\" .It Ic touch Ar MTIME FILE
.\" Set the last modified timestamp of
.\" .Ar FILE
.\" to
.\" .Ar MTIME
.\" (in seconds since epoch).
.\" If
.\" .Ar FILE
.\" doesn't exist, an empty file is created.
.\" .It Ic ulimit Ar C VALUE
.\" Set
.\" .Xr ulimit 1
.\" flag
.\" .Fl Ar C
.\" to
.\" .Ar VALUE
.\" while running the program.
.\" E.g.,
.\" .Dl ulimit n 16
.\" would run the equivalent of the
.\" .Xr sh 1
.\" command
.\" .Dl ulimit -n 16 .
.El
.Sh SEE ALSO
.Xr nihtest 1 ,
.Xr nihtest-config 5
