name: build
on: [push]

jobs:
  all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare build directory
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
      - name: configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake ${{github.workspace}}
      - name: build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config Release
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest -v -C Release
