name: build
on: [push]
permissions:
  contents: read
jobs:
  all:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        cmake_extra: [""]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python and pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: prepare build directory
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
      - name: configure (Unix)
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake ${{ matrix.cmake_extra }} ${{github.workspace}}
      - name: build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config Release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-directory-${{ matrix.os }}
          path: |
            ${{runner.workspace}}/build/tests
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --output-on-failure -v -C Release
